INSERT INTO CUSTOMERS(CUSTOMER_NAME, CUSTOMER_EMAIL, PASSWORD) VALUES('Ben1', 'Ben@Ben.com', 'pass');
INSERT INTO CUSTOMERS(CUSTOMER_NAME, CUSTOMER_EMAIL, PASSWORD) VALUES('Ben2', 'Ben@Ben.com', 'pass');
INSERT INTO CUSTOMERS(CUSTOMER_NAME, CUSTOMER_EMAIL, PASSWORD) VALUES('Ben3', 'Ben@Ben.com', 'pass');

INSERT INTO EVENTS(CUSTOMER_NAME, CUSTOMER_EMAIL, PASSWORD) VALUES('Ben1', 'Ben@Ben.com', 'pass');
INSERT INTO EVENTS(CUSTOMER_NAME, CUSTOMER_EMAIL, PASSWORD) VALUES('Ben2', 'Ben@Ben.com', 'pass');
INSERT INTO EVENTS(CUSTOMER_NAME, CUSTOMER_EMAIL, PASSWORD) VALUES('Ben3', 'Ben@Ben.com', 'pass');

INSERT INTO REGISTRATIONS(CUSTOMER_NAME, CUSTOMER_EMAIL, PASSWORD) VALUES('Ben1', 'Ben@Ben.com', 'pass');
INSERT INTO REGISTRATIONS(CUSTOMER_NAME, CUSTOMER_EMAIL, PASSWORD) VALUES('Ben2', 'Ben@Ben.com', 'pass');
INSERT INTO REGISTRATIONS(CUSTOMER_NAME, CUSTOMER_EMAIL, PASSWORD) VALUES('Ben3', 'Ben@Ben.com', 'pass');